/**
 * Generate yclaw.config.yaml from a ResolvedInitPlan.
 *
 * CRITICAL: The generated file must pass YclawConfigSchema.parse() (core strict schema).
 * Only core-recognized fields (storage, secrets, channels) go into the YAML body.
 * CLI-specific metadata (deployment, llm, networking, observability) is written
 * as comments for human reference — not as YAML keys.
 */

import { stringify } from 'yaml';
import type { ResolvedInitPlan } from '../types.js';

export function generateConfigYaml(plan: ResolvedInitPlan): string {
  // Extract only core-schema fields — these are what the runtime reads
  const coreConfig: Record<string, unknown> = {
    storage: plan.config.storage,
    secrets: plan.config.secrets,
    channels: plan.config.channels,
  };

  // Include communication config if non-default
  if (plan.config.communication) {
    coreConfig.communication = plan.config.communication;
  }

  const header = [
    '# Generated by: yclaw init',
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '# Docs: https://github.com/YClawAI/yclaw',
    '#',
    '# CLI metadata (not parsed by runtime):',
    `#   deployment: ${plan.config.deployment?.target ?? 'not set'}`,
    `#   llm: ${plan.config.llm?.defaultProvider ?? 'anthropic'} (${plan.config.llm?.defaultModel ?? 'default'})`,
    `#   networking: api=${plan.config.networking?.apiPort ?? 3000}`,
    `#   observability: ${plan.config.observability?.logLevel ?? 'info'}`,
    '',
  ].join('\n');

  const yaml = stringify(coreConfig, {
    lineWidth: 100,
    nullStr: '',
  });

  return header + yaml;
}
