/**
 * Generate docker-compose.yaml from a ResolvedInitPlan.
 * Only called when deployment target is docker-compose.
 */

import { stringify } from 'yaml';
import type { ResolvedInitPlan } from '../types.js';

export function generateDockerCompose(plan: ResolvedInitPlan): string {
  if (!plan.compose) {
    throw new Error('Cannot generate docker-compose: no compose spec in plan');
  }

  const header = [
    '# Generated by: yclaw init',
    '# Regenerate with: yclaw init --preset <preset> --force',
    '',
  ].join('\n');

  const yaml = stringify(plan.compose, {
    lineWidth: 100,
    nullStr: '',
  });

  return header + yaml;
}
