/**
 * Generate .env from a ResolvedInitPlan.
 * Only includes keys relevant to the user's configuration.
 */

import type { ResolvedInitPlan } from '../types.js';

export function generateEnvFile(plan: ResolvedInitPlan): string {
  const lines: string[] = [
    '# Generated by: yclaw init',
    `# Date: ${new Date().toISOString().split('T')[0]}`,
    '# See .env.example for the full list of available variables.',
    '',
  ];

  // Group by category
  const groups: Array<{ label: string; keys: string[] }> = [
    {
      label: 'Core Runtime',
      keys: ['NODE_ENV', 'PORT', 'API_PORT'],
    },
    {
      label: 'Database',
      keys: ['MONGODB_URI', 'REDIS_URL', 'MEMORY_DATABASE_URL'],
    },
    {
      label: 'LLM Provider',
      keys: ['ANTHROPIC_API_KEY', 'OPENAI_API_KEY', 'OPENROUTER_API_KEY'],
    },
    {
      label: 'Channels',
      keys: [
        'SLACK_BOT_TOKEN',
        'TELEGRAM_BOT_TOKEN',
        'DISCORD_BOT_TOKEN',
        'TWITTER_APP_KEY',
        'TWITTER_APP_SECRET',
        'TWITTER_ACCESS_TOKEN',
        'TWITTER_ACCESS_SECRET',
      ],
    },
    {
      label: 'AWS (if applicable)',
      keys: ['YCLAW_S3_BUCKET', 'AWS_REGION'],
    },
    {
      label: 'Security',
      keys: ['EVENT_BUS_SECRET', 'YCLAW_SETUP_TOKEN'],
    },
    {
      label: 'Docker Compose',
      keys: ['COMPOSE_PROFILES', 'POSTGRES_PASSWORD'],
    },
    {
      label: 'Mission Control',
      keys: ['MC_PORT', 'NEXTAUTH_SECRET', 'NEXTAUTH_URL'],
    },
    {
      label: 'Autonomy Defaults',
      keys: ['GOVERNANCE_MODE', 'REACTION_LOOP_ENABLED', 'BUDGET_ENFORCEMENT_ENABLED'],
    },
    {
      label: 'GitHub',
      keys: [
        'GITHUB_OWNER',
        'GITHUB_REPO',
        'GITHUB_APP_ID',
        'GITHUB_APP_PRIVATE_KEY',
        'GITHUB_APP_INSTALLATION_ID',
        'GITHUB_TOKEN',
      ],
    },
    {
      label: 'Agent Orchestrator',
      keys: [
        'AO_SERVICE_URL',
        'AO_AUTH_TOKEN',
        'AO_CALLBACK_URL',
        'AO_MAX_CONCURRENT',
        'YCLAW_AO_PROJECT',
        'YCLAW_REPOS',
      ],
    },
  ];

  for (const group of groups) {
    const presentKeys = group.keys.filter(k => k in plan.env);
    if (presentKeys.length === 0) continue;

    lines.push(`# ${group.label}`);
    for (const key of presentKeys) {
      const value = plan.env[key] ?? '';
      // Empty values are placeholders the user needs to fill in
      if (value === '') {
        lines.push(`# TODO: fill in ${key}`);
        lines.push(`${key}=`);
      } else if (/[#\s"'\\$`!]/.test(value)) {
        // Quote values with special characters
        const escaped = value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
        lines.push(`${key}="${escaped}"`);
      } else {
        lines.push(`${key}=${value}`);
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}
