/**
 * Builder Dispatcher-Worker Architecture Types
 *
 * Defines the type system for the priority task queue, worker pool,
 * and dispatcher orchestration layer that replaces the monolithic
 * Builder agent execution model.
 */

// ─── Priority Levels ─────────────────────────────────────────────────────────

/**
 * Task priority levels for the Builder dispatcher queue.
 *
 * Lower numeric value = higher priority.
 *   P0: Safety/error fixes — CI failures, security issues
 *   P1: Code reviews — PR review responses, human review feedback
 *   P2: Implementation — issue implementation, directives, bug fixes
 *   P3: Background — refactoring, tech debt, standup reports
 */
export enum Priority {
  P0_SAFETY = 0,
  P1_REVIEW = 1,
  P2_IMPLEMENTATION = 2,
  P3_BACKGROUND = 3,
}

// ─── Task State ──────────────────────────────────────────────────────────────

export enum TaskState {
  QUEUED = 'queued',
  ASSIGNED = 'assigned',
  RUNNING = 'running',
  COMPLETED = 'completed',
  FAILED = 'failed',
  TIMEOUT = 'timeout',
  /** Task was valid but not actionable (e.g. review approved, PR already closed).
   *  Acknowledged immediately — no DLQ entry, no retry. */
  SKIPPED = 'skipped',
  /** Task was in-flight during SIGTERM and re-queued for retry after restart. */
  REQUEUED = 'requeued',
}

export type TaskFailureReason = 'sigterm' | 'timeout' | 'error' | 'circuit_breaker';

// ─── Builder Task ────────────────────────────────────────────────────────────

export interface BuilderTask {
  /** Unique task ID (UUID). */
  id: string;
  /** Priority level for queue ordering. */
  priority: Priority;
  /** Current state in the task lifecycle. */
  state: TaskState;
  /** The agent task name to execute (e.g., 'implement_issue', 'fix_ci_failure'). */
  taskName: string;
  /** Event payload from the trigger that created this task. */
  triggerPayload: Record<string, unknown>;
  /** The event type that originated this task (e.g., 'github:issue_assigned'). */
  sourceEvent: string;
  /** Correlation ID for end-to-end tracing. */
  correlationId: string;
  /** ID of the worker handling this task (set when assigned). */
  workerId?: string;
  /** When the task was created. */
  createdAt: string;
  /** When the task was assigned to a worker. */
  assignedAt?: string;
  /** When the task completed (success or failure). */
  completedAt?: string;
  /** Error message if the task failed. */
  error?: string;
  /** Timeout in milliseconds for this task. */
  timeoutMs: number;
  /** DLQ retry attempts already performed for this task (0 = first failure). */
  dlqRetryCount?: number;
  /** Immediate timeout retry count (0 = first attempt, 1 = retry). Tasks retry
   *  once on timeout before being sent to DLQ. */
  timeoutRetryCount?: number;
  /** Optional model override for this task (from cron or event trigger config). */
  modelOverride?: import('../config/schema.js').ModelConfig;

  // ─── ACP Session Fields ────────────────────────────────────────────────────

  /**
   * ACP session ID. Generated by Dispatcher on enqueue; reused for iterative
   * tasks on the same thread. Format: `ses_<20-char hex>` (ACP) or `cli_<taskId>` (CLI).
   */
  sessionId?: string;

  /**
   * Thread ID for grouping iterative tasks (e.g., PR number, CI run ID).
   * Deterministic: SHA-256 of (repoUrl + prNumber + taskType), first 32 hex chars.
   * Tasks with the same threadId reuse the same ACP session.
   */
  threadId?: string;

  /**
   * Executor preference for this task.
   *   'cli'  — Force legacy CLI path
   *   'pi'   — Force Pi executor
   *   'auto' — Prefer Pi when enabled, else CLI
   */
  executorHint?: 'cli' | 'pi' | 'auto';

  /**
   * Coding harness override for this task.
   * Falls back to executor config defaultHarness when not set.
   */
  harness?: import('../codegen/backends/types.js').HarnessType;

  /**
   * Model name override for the executor session (string, e.g. 'claude-sonnet-4-6').
   * Distinct from modelOverride (ModelConfig) which is used by AgentExecutor.
   */
  sessionModel?: string;

  /**
   * Pre-formatted coding prompt for the executor session's first turn.
   * Set by the Dispatcher when enough context is available from triggerPayload.
   * If absent, the worker falls back to AgentExecutor-based execution.
   */
  prompt?: string;

  /**
   * Local repo path for the executor session.
   * Extracted from triggerPayload.repo or repoConfig lookup.
   */
  repoPath?: string;

  /**
   * Steer instruction for follow-up turns on an existing session.
   * Set when re-enqueueing a task against an existing threadId session.
   * If present, the worker calls executor.steer() instead of executor.sendMessage().
   */
  steerInstruction?: string;

  /**
   * Additional context for steering (CI logs, review comments, diff, etc.).
   * Injected as JSON into the steer prompt.
   */
  steerContext?: Record<string, unknown>;
}

// ─── Worker Handle ───────────────────────────────────────────────────────────

export type WorkerState = 'idle' | 'busy' | 'stopping';

export interface WorkerHandle {
  /** Unique worker ID. */
  id: string;
  /** Current worker state. */
  state: WorkerState;
  /** ID of the task currently being processed (null if idle). */
  currentTaskId: string | null;
  /** When the worker was created. */
  createdAt: string;
  /** When the worker started its current task. */
  taskStartedAt?: string;
  /** Abort controller for cancelling the current task. */
  abortController?: AbortController;
}

// ─── Dead-Letter Queue ───────────────────────────────────────────────────────

export interface DlqEntry {
  taskId: string;
  taskName: string;
  correlationId: string;
  priority: number;
  sourceEvent: string;
  error: string;
  failedAt: string;
  durationMs: number | null;
  /** Number of DLQ retry attempts so far (0 = first failure). */
  retryCount: number;
  /** ISO timestamp — earliest time this entry is eligible for retry. */
  nextRetryAt: string;
  /** Max retries before marking permanent. */
  maxRetries: number;
  /** When true, entry has exhausted retries and needs manual intervention. */
  permanent: boolean;
  /** Original trigger payload for re-enqueue on retry. */
  triggerPayload?: Record<string, unknown>;
}

// ─── Dispatcher Metrics ──────────────────────────────────────────────────────

export interface DispatcherMetrics {
  timestamp: string;
  workers: { total: number; idle: number; busy: number };
  queue: { total: number; byPriority: { P0: number; P1: number; P2: number; P3: number } };
  recentTasks: {
    completed: number;
    failed: number;
    timedOut: number;
    requeued: number;
    avgDurationMs: number | null;
    p95DurationMs: number | null;
  };
  dlq: { depth: number; entries: DlqEntry[] };
}

// ─── Dispatcher Configuration ────────────────────────────────────────────────

export interface DispatcherConfig {
  /** Maximum number of concurrent workers. */
  maxConcurrentWorkers: number;
  /** Default timeout per task in milliseconds. */
  defaultTimeoutMs: number;
  /** Redis key prefix for the task queue sorted set. */
  queueKey: string;
  /** Redis key prefix for task state hashes. */
  taskKeyPrefix: string;
  /** Mapping of task names to priority levels. */
  priorityMap: Record<string, Priority>;
  /** How often to poll the queue for new tasks (ms). */
  pollIntervalMs: number;
  /** TTL for completed task records in Redis (seconds). */
  completedTaskTtlSecs: number;
  /** Age (ms) a P3 task must be queued before it is promoted past P1/P2. 0 = disabled. */
  promotionAgeMs: number;
  /** Redis list key for the dead-letter queue. */
  dlqKey: string;
  /** Maximum number of entries to retain in the DLQ (oldest trimmed). */
  dlqMaxSize: number;
  /** How often to check DLQ for retryable entries (ms). Default: 5 min. */
  dlqRetryIntervalMs: number;
  /** Maximum number of DLQ retry attempts before marking permanent. Default: 3. */
  dlqMaxRetries: number;
  /** Total queue depth at which ALL tasks except P0 are rejected. Default: 50. */
  maxQueueDepth: number;
  /** Queue depth at which P3 tasks are rejected. Default: 30. */
  backpressureThreshold: number;
  /** Maximum age (ms) for a correlation ID before the task is considered stale. Default: 2h. */
  correlationMaxAgeMs: number;
}

export const DEFAULT_DISPATCHER_CONFIG: DispatcherConfig = {
  maxConcurrentWorkers: 3,
  defaultTimeoutMs: 10 * 60 * 1000, // 10 minutes
  queueKey: 'builder:task_queue',
  taskKeyPrefix: 'builder:task:',
  priorityMap: {
    fix_ci_failure: Priority.P0_SAFETY,
    address_review_feedback: Priority.P1_REVIEW,
    address_human_review: Priority.P1_REVIEW,
    implement_issue: Priority.P2_IMPLEMENTATION,
    implement_directive: Priority.P2_IMPLEMENTATION,
    daily_standup: Priority.P3_BACKGROUND,
    self_reflection: Priority.P3_BACKGROUND,
  },
  pollIntervalMs: 2000,
  completedTaskTtlSecs: 3600, // 1 hour
  promotionAgeMs: Number(process.env.BUILDER_P3_PROMOTION_AGE_MS ?? 30 * 60 * 1000),
  dlqKey: 'builder:dlq',
  dlqMaxSize: Number(process.env.BUILDER_DLQ_MAX_SIZE ?? 100),
  dlqRetryIntervalMs: Number(process.env.BUILDER_DLQ_RETRY_INTERVAL_MS ?? 60 * 1000),
  dlqMaxRetries: Number(process.env.BUILDER_DLQ_MAX_RETRIES ?? 3),
  maxQueueDepth: Number(process.env.BUILDER_MAX_QUEUE_DEPTH ?? 50),
  backpressureThreshold: Number(process.env.BUILDER_BACKPRESSURE_THRESHOLD ?? 30),
  correlationMaxAgeMs: Number(process.env.BUILDER_CORRELATION_MAX_AGE_MS ?? 2 * 60 * 60 * 1000), // 2 hours
};

// ─── Event-to-Task Mapping ───────────────────────────────────────────────────

/**
 * Maps event types to the Builder task names they should trigger.
 * Used by the dispatcher to classify incoming events.
 */
export const EVENT_TASK_MAP: Record<string, string> = {
  'architect:build_directive': 'implement_directive',
  'strategist:builder_directive': 'implement_directive',
  'github:pr_review_comment': 'address_review_feedback',
  'github:ci_fail': 'fix_ci_failure',
  'github:pr_review_submitted': 'address_human_review',
  'claudeception:reflect': 'self_reflection',
};
