import { createLogger } from '../logging/logger.js';
import { getGitHubToken, isGitHubAuthAvailable } from '../actions/github/app-auth.js';

const logger = createLogger('config-persister');

const GITHUB_API = 'https://api.github.com';
const OWNER = 'yclaw-ai';
const REPO = 'yclaw';
const BASE_BRANCH = 'master';

/**
 * Persists agent config changes to GitHub via the Contents API.
 * Creates a branch + commit + PR so changes survive container restarts.
 *
 * Gracefully degrades: if GitHub API fails, logs warning but doesn't
 * block the local filesystem write that already happened.
 */
export class ConfigPersister {
  constructor() {
    if (!isGitHubAuthAvailable()) {
      logger.warn('GitHub auth not configured — config changes will not persist to Git');
    }
  }

  /**
   * Persist a config file change by creating a branch, committing, and opening a PR.
   */
  async persistConfigChange(opts: {
    agentName: string;
    department: string;
    fileContent: string;
    description: string;
  }): Promise<{ success: boolean; prUrl?: string; error?: string }> {
    if (!isGitHubAuthAvailable()) {
      return { success: false, error: 'No GitHub auth available' };
    }

    const { agentName, department, fileContent, description } = opts;
    const filePath = `departments/${department}/${agentName}.yaml`;
    const branchName = `agent/${agentName}-config-${Date.now()}`;

    try {
      // 1. Get the SHA of the base branch
      const baseSha = await this.getBranchSha(BASE_BRANCH);
      if (!baseSha) {
        throw new Error(`Could not get SHA for ${BASE_BRANCH}`);
      }

      // 2. Create a new branch from base
      await this.createBranch(branchName, baseSha);

      // 3. Get the current file SHA (needed for update)
      const fileSha = await this.getFileSha(filePath, BASE_BRANCH);

      // 4. Commit the updated file to the new branch
      const contentBase64 = Buffer.from(fileContent, 'utf-8').toString('base64');
      await this.commitFile({
        path: filePath,
        content: contentBase64,
        message: `config(${agentName}): ${description}`,
        branch: branchName,
        sha: fileSha,
      });

      // 5. Create the PR
      const prUrl = await this.createPR({
        title: `config(${agentName}): ${description}`,
        body: [
          `## Self-Modification PR`,
          ``,
          `**Agent:** ${agentName}`,
          `**Department:** ${department}`,
          `**Change:** ${description}`,
          ``,
          `This PR was auto-generated by the agent's self-modification system.`,
          `Approve and merge to persist the change.`,
        ].join('\n'),
        head: branchName,
        base: BASE_BRANCH,
      });

      logger.info(`Config change PR created for ${agentName}`, { prUrl, description });
      return { success: true, prUrl };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.error(`Failed to persist config change for ${agentName}`, { error: msg });
      return { success: false, error: msg };
    }
  }

  private async getBranchSha(branch: string): Promise<string | null> {
    const res = await this.api('GET', `/repos/${OWNER}/${REPO}/git/ref/heads/${branch}`);
    if (!res.ok) return null;
    const data = (await res.json()) as { object: { sha: string } };
    return data.object.sha;
  }

  private async createBranch(name: string, sha: string): Promise<void> {
    const res = await this.api('POST', `/repos/${OWNER}/${REPO}/git/refs`, {
      ref: `refs/heads/${name}`,
      sha,
    });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(`Failed to create branch ${name}: ${res.status} ${body}`);
    }
  }

  private async getFileSha(path: string, branch: string): Promise<string | undefined> {
    const res = await this.api('GET', `/repos/${OWNER}/${REPO}/contents/${path}?ref=${branch}`);
    if (!res.ok) return undefined;
    const data = (await res.json()) as { sha: string };
    return data.sha;
  }

  private async commitFile(opts: {
    path: string;
    content: string;
    message: string;
    branch: string;
    sha?: string;
  }): Promise<void> {
    const body: Record<string, unknown> = {
      message: opts.message,
      content: opts.content,
      branch: opts.branch,
    };
    if (opts.sha) body.sha = opts.sha;

    const res = await this.api('PUT', `/repos/${OWNER}/${REPO}/contents/${opts.path}`, body);
    if (!res.ok) {
      const errBody = await res.text();
      throw new Error(`Failed to commit ${opts.path}: ${res.status} ${errBody}`);
    }
  }

  private async createPR(opts: {
    title: string;
    body: string;
    head: string;
    base: string;
  }): Promise<string> {
    const res = await this.api('POST', `/repos/${OWNER}/${REPO}/pulls`, opts);
    if (!res.ok) {
      const errBody = await res.text();
      throw new Error(`Failed to create PR: ${res.status} ${errBody}`);
    }
    const data = (await res.json()) as { html_url: string };
    return data.html_url;
  }

  private async api(
    method: string,
    path: string,
    body?: Record<string, unknown>,
  ): Promise<Response> {
    const token = await getGitHubToken();
    const url = `${GITHUB_API}${path}`;
    const headers: Record<string, string> = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };
    if (body) headers['Content-Type'] = 'application/json';

    return fetch(url, {
      method,
      headers,
      body: body ? JSON.stringify(body) : undefined,
    });
  }
}
