/**
 * Environment variable secret backend — writes to .env.integrations file.
 *
 * Simplest backend for local development. Credentials are stored as
 * environment variables in KEY=value format. No encryption — intended
 * for development only.
 *
 * Requires: SECRETS_ENV_FILE (defaults to .env.integrations)
 */

import fs from 'node:fs';
import path from 'node:path';
import { randomUUID } from 'crypto';
import type { SecretBackend } from '../secret-backend.js';

export class EnvSecretBackend implements SecretBackend {
  private readonly filePath: string;

  constructor(filePath?: string) {
    this.filePath = filePath ??
      process.env.SECRETS_ENV_FILE ??
      path.resolve(process.cwd(), '.env.integrations');
  }

  private readAll(): Record<string, string> {
    if (!fs.existsSync(this.filePath)) return {};
    const content = fs.readFileSync(this.filePath, 'utf-8');
    const entries: Record<string, string> = {};
    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx < 0) continue;
      entries[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
    return entries;
  }

  private writeAll(entries: Record<string, string>): void {
    const dir = path.dirname(this.filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

    const lines = ['# Auto-generated by EnvSecretBackend — do not edit manually'];
    for (const [key, value] of Object.entries(entries)) {
      lines.push(`${key}=${value}`);
    }
    fs.writeFileSync(this.filePath, lines.join('\n') + '\n', 'utf-8');
  }

  private envKey(integration: string, field: string, groupId?: string): string {
    const base = `INTEGRATION_${integration.toUpperCase().replace(/-/g, '_')}_${field.toUpperCase()}`;
    // Include groupId suffix for session-scoped isolation
    if (groupId) return `${base}_${groupId.replace(/-/g, '_').slice(0, 8)}`;
    return base;
  }

  async store(integration: string, fields: Record<string, string>): Promise<string> {
    const entries = this.readAll();
    const groupId = randomUUID();

    // Store each field as a session-scoped env var
    for (const [key, value] of Object.entries(fields)) {
      if (!value) continue;
      const envKey = this.envKey(integration, key, groupId);
      entries[envKey] = value;
      process.env[envKey] = value;
      // Also write the non-scoped key for runtime convenience (latest wins)
      entries[this.envKey(integration, key)] = value;
      process.env[this.envKey(integration, key)] = value;
    }
    // Store the group mapping with the groupId-scoped keys
    entries[`INTEGRATION_GROUP_${groupId.replace(/-/g, '_')}`] = [
      integration,
      groupId,
      ...Object.keys(fields).filter((k) => fields[k]),
    ].join(',');

    this.writeAll(entries);
    return groupId;
  }

  async retrieve(ref: string): Promise<Record<string, string> | null> {
    const entries = this.readAll();
    const groupKey = `INTEGRATION_GROUP_${ref.replace(/-/g, '_')}`;
    const mapping = entries[groupKey];
    if (!mapping) return null;

    const parts = mapping.split(',');
    const integration = parts[0]!;
    const groupId = parts[1]!;
    const fieldKeys = parts.slice(2);

    const result: Record<string, string> = {};
    for (const key of fieldKeys) {
      // Try session-scoped key first, then generic
      const scopedKey = this.envKey(integration, key, groupId);
      const genericKey = this.envKey(integration, key);
      const val = entries[scopedKey] ?? process.env[scopedKey] ?? entries[genericKey] ?? process.env[genericKey];
      if (val) result[key] = val;
    }
    return Object.keys(result).length > 0 ? result : null;
  }

  async retrieveField(scopedRef: string): Promise<string | null> {
    // scopedRef format: integrations/{integration}/{groupId}/{field}
    const parts = scopedRef.split('/');
    if (parts.length < 4) return null;
    const integration = parts[1]!;
    const groupId = parts[2]!;
    const field = parts[3]!;
    // Try session-scoped key first, then generic
    const scopedKey = this.envKey(integration, field, groupId);
    const genericKey = this.envKey(integration, field);
    const entries = this.readAll();
    return entries[scopedKey] ?? process.env[scopedKey] ?? entries[genericKey] ?? process.env[genericKey] ?? null;
  }

  async delete(ref: string): Promise<void> {
    const entries = this.readAll();
    const groupKey = `INTEGRATION_GROUP_${ref.replace(/-/g, '_')}`;
    const mapping = entries[groupKey];
    if (!mapping) return;

    const parts = mapping.split(',');
    const integration = parts[0]!;
    const fieldKeys = parts.slice(1);

    for (const key of fieldKeys) {
      const envKey = this.envKey(integration, key);
      delete entries[envKey];
      delete process.env[envKey];
    }
    delete entries[groupKey];
    this.writeAll(entries);
  }

  async list(): Promise<string[]> {
    const entries = this.readAll();
    return Object.keys(entries)
      .filter((k) => k.startsWith('INTEGRATION_GROUP_'))
      .map((k) => k.replace('INTEGRATION_GROUP_', '').replace(/_/g, '-'));
  }
}
