/**
 * Env contract validation test.
 * Ensures the docker-compose.yml env_file references and the CLI env generation
 * share the same variable names. Prevents drift between the compose file and
 * the CLI's env output.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { resolveInitPlan } from '../src/plan/resolve.js';
import { getPreset } from '../src/presets/index.js';

// Resolve paths relative to monorepo root (packages/cli/tests/ → ../../..)
const __dirname = resolve(fileURLToPath(import.meta.url), '..');
const REPO_ROOT = resolve(__dirname, '..', '..', '..');

/**
 * Extract environment variable names referenced in a docker-compose.yml.
 * Matches ${VAR_NAME}, ${VAR_NAME:-default}, and $VAR_NAME patterns.
 */
function extractComposeEnvVars(content: string): Set<string> {
  const vars = new Set<string>();
  const patterns = [
    /\$\{(\w+)(?::-[^}]*)?\}/g,   // ${VAR:-default} or ${VAR}
    /\$([A-Z_][A-Z0-9_]*)/g,       // $VAR (only UPPER_CASE to avoid false positives)
  ];
  for (const pattern of patterns) {
    let match;
    while ((match = pattern.exec(content)) !== null) {
      vars.add(match[1]!);
    }
  }
  return vars;
}

describe('env contract', () => {
  it('compose file env vars are a subset of CLI-generated env vars (for bundled mode)', () => {
    const composePath = resolve(REPO_ROOT, 'deploy/docker-compose/docker-compose.yml');
    const composeContent = readFileSync(composePath, 'utf-8');
    const composeVars = extractComposeEnvVars(composeContent);

    // Generate env from local-demo preset (docker-compose target)
    const preset = getPreset('local-demo');
    const plan = resolveInitPlan(preset);
    const cliVars = new Set(Object.keys(plan.env));

    // These vars are used by compose itself or are Docker builtins — not in .env
    // Vars that are compose-internal or have defaults — not expected in CLI .env
    const composeInternalVars = new Set([
      'YCLAW_VERSION',                // Image tag, set by operator
      'YCLAW_API_URL',                // Hardcoded in compose (server-side MC → core)
      'NEXT_PUBLIC_YCLAW_API_URL',    // Hardcoded in compose (client-side MC → core)
      'HOSTNAME',                     // Hardcoded in compose
      'POSTGRES_DB',                  // Hardcoded in compose
      'POSTGRES_USER',                // Hardcoded in compose
      'AO_BRIDGE_PORT',              // Compose default :-8420
      'AO_DASHBOARD_PORT',           // Compose default :-3002
      'YCLAW_REPOS',                 // Compose default :-YClawAI/YClaw
      'AO_MAX_CONCURRENT',           // Compose default :-2
      'AO_CALLBACK_URL',             // Hardcoded in compose (AO → core)
      'AO_AUTH_TOKEN',               // Operator-provided, not generated by CLI
      'GITHUB_APP_ID',               // Operator-provided, not generated by CLI
      'GITHUB_APP_PRIVATE_KEY',      // Operator-provided, not generated by CLI
      'GITHUB_APP_INSTALLATION_ID',  // Operator-provided, not generated by CLI
    ]);

    const missingVars: string[] = [];
    for (const v of composeVars) {
      if (!cliVars.has(v) && !composeInternalVars.has(v)) {
        missingVars.push(v);
      }
    }

    expect(
      missingVars,
      `Compose file references env vars not generated by CLI: ${missingVars.join(', ')}`,
    ).toHaveLength(0);
  });

  it('.env.example covers all compose env vars', () => {
    const composePath = resolve(REPO_ROOT, 'deploy/docker-compose/docker-compose.yml');
    const composeContent = readFileSync(composePath, 'utf-8');
    const composeVars = extractComposeEnvVars(composeContent);

    const examplePath = resolve(REPO_ROOT, 'deploy/docker-compose/.env.example');
    const exampleContent = readFileSync(examplePath, 'utf-8');

    // Variables referenced or documented in .env.example
    const exampleVars = new Set<string>();
    for (const line of exampleContent.split('\n')) {
      const match = /^#?\s*([A-Z_][A-Z0-9_]*)=/.exec(line);
      if (match) exampleVars.add(match[1]!);
    }

    const composeInternalVars = new Set([
      'NEXT_PUBLIC_API_URL',
      'HOSTNAME',
      'POSTGRES_DB',
      'POSTGRES_USER',
      'AO_BRIDGE_PORT',              // Compose default :-8420
      'AO_DASHBOARD_PORT',           // Compose default :-3002
      'YCLAW_REPOS',                 // Compose default :-YClawAI/YClaw
      'AO_MAX_CONCURRENT',           // Compose default :-2
      'AO_CALLBACK_URL',             // Hardcoded in compose (AO → core)
    ]);

    const missing: string[] = [];
    for (const v of composeVars) {
      if (!exampleVars.has(v) && !composeInternalVars.has(v)) {
        missing.push(v);
      }
    }

    expect(
      missing,
      `.env.example is missing compose vars: ${missing.join(', ')}`,
    ).toHaveLength(0);
  });

  it('YCLAW_SETUP_TOKEN is generated for docker-compose preset', () => {
    const preset = getPreset('local-demo');
    const plan = resolveInitPlan(preset);
    expect(plan.env.YCLAW_SETUP_TOKEN).toBeDefined();
    expect(plan.env.YCLAW_SETUP_TOKEN!.length).toBeGreaterThanOrEqual(32);
  });

  it('COMPOSE_PROFILES=bundled is set for docker-compose preset', () => {
    const preset = getPreset('local-demo');
    const plan = resolveInitPlan(preset);
    expect(plan.env.COMPOSE_PROFILES).toBe('bundled');
  });

  it('manual preset does NOT set COMPOSE_PROFILES', () => {
    const preset = getPreset('aws-production');
    const plan = resolveInitPlan(preset);
    expect(plan.env.COMPOSE_PROFILES).toBeUndefined();
  });
});
