import { describe, it, expect } from 'vitest';
import { parse as parseYaml } from 'yaml';
import { getPreset, listPresets } from '../src/presets/index.js';
import { resolveInitPlan } from '../src/plan/resolve.js';
import { generateConfigYaml } from '../src/generators/config-yaml.js';
import { generateEnvFile } from '../src/generators/env-file.js';
import { generateDockerCompose } from '../src/generators/docker-compose.js';
import { CliConfigSchema } from '../src/schema/cli-config-schema.js';

describe('generateConfigYaml', () => {
  for (const name of listPresets()) {
    it(`${name}: generates valid YAML that round-trips through schema`, () => {
      const plan = resolveInitPlan(getPreset(name));
      const yaml = generateConfigYaml(plan);

      // Must be valid YAML
      const parsed = parseYaml(yaml);
      expect(parsed).toBeDefined();

      // Must validate against CLI schema
      expect(() => CliConfigSchema.parse(parsed)).not.toThrow();
    });
  }

  it('includes header comment', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const yaml = generateConfigYaml(plan);
    expect(yaml).toContain('# Generated by: yclaw init');
  });

  it('never contains credential values', () => {
    const preset = getPreset('small-team');
    preset.credentials = { SLACK_BOT_TOKEN: 'xoxb-secret-123' };
    const plan = resolveInitPlan(preset);
    const yaml = generateConfigYaml(plan);
    expect(yaml).not.toContain('xoxb-secret-123');
  });
});

describe('generateEnvFile', () => {
  it('local-demo: includes database URIs', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const env = generateEnvFile(plan);
    expect(env).toContain('MONGODB_URI=');
    expect(env).toContain('REDIS_URL=');
    expect(env).toContain('MEMORY_DATABASE_URL=');
  });

  it('includes LLM API key placeholder', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const env = generateEnvFile(plan);
    expect(env).toContain('ANTHROPIC_API_KEY=');
  });

  it('small-team: includes SLACK_BOT_TOKEN', () => {
    const plan = resolveInitPlan(getPreset('small-team'));
    const env = generateEnvFile(plan);
    expect(env).toContain('SLACK_BOT_TOKEN=');
  });

  it('includes EVENT_BUS_SECRET', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const env = generateEnvFile(plan);
    expect(env).toMatch(/EVENT_BUS_SECRET=[0-9a-f]{64}/);
  });

  it('includes Mission Control auth secret for docker-compose installs', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const env = generateEnvFile(plan);
    expect(env).toMatch(/NEXTAUTH_SECRET=[0-9a-f]{64}/);
    expect(env).toContain('NEXTAUTH_URL=http://localhost:3001');
  });

  it('includes header comment', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const env = generateEnvFile(plan);
    expect(env).toContain('# Generated by: yclaw init');
  });
});

describe('generateDockerCompose', () => {
  it('local-demo: generates valid YAML with all services', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const yaml = generateDockerCompose(plan);
    const parsed = parseYaml(yaml);

    expect(parsed.services.yclaw).toBeDefined();
    expect(parsed.services['mission-control']).toBeDefined();
    expect(parsed.services.ao).toBeDefined();
    expect(parsed.services.mongodb).toBeDefined();
    expect(parsed.services.redis).toBeDefined();
    expect(parsed.services.postgres).toBeDefined();
  });

  it('services have healthchecks', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const yaml = generateDockerCompose(plan);
    const parsed = parseYaml(yaml);

    expect(parsed.services.mongodb.healthcheck).toBeDefined();
    expect(parsed.services.redis.healthcheck).toBeDefined();
    expect(parsed.services.postgres.healthcheck).toBeDefined();
    expect(parsed.services.ao.healthcheck).toBeDefined();
    expect(parsed.services['mission-control'].healthcheck).toBeDefined();
  });

  it('yclaw service depends on all infrastructure', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const yaml = generateDockerCompose(plan);
    const parsed = parseYaml(yaml);

    expect(parsed.services.yclaw.depends_on.mongodb).toBeDefined();
    expect(parsed.services.yclaw.depends_on.redis).toBeDefined();
    expect(parsed.services.yclaw.depends_on.postgres).toBeDefined();
    expect(parsed.services.ao.depends_on.yclaw).toBeDefined();
    expect(parsed.services['mission-control'].depends_on.yclaw).toBeDefined();
  });

  it('has named volumes', () => {
    const plan = resolveInitPlan(getPreset('local-demo'));
    const yaml = generateDockerCompose(plan);
    const parsed = parseYaml(yaml);

    expect(parsed.volumes).toBeDefined();
    expect('mongodb-data' in parsed.volumes).toBe(true);
    expect('redis-data' in parsed.volumes).toBe(true);
    expect('postgres-data' in parsed.volumes).toBe(true);
    expect('ao-data' in parsed.volumes).toBe(true);
  });

  it('throws for non-docker-compose plans', () => {
    const plan = resolveInitPlan(getPreset('aws-production'));
    expect(() => generateDockerCompose(plan)).toThrow();
  });
});
